config/routes.rb
Rails.application.routes.draw do
  resources :libraries

  get 'libraries/participation/:id' => 'libraries#participation', as: :library_participation

  resources :scenarios do
    resources :implementations
  end

  put 'implementations/:id/add_stats' => 'implementations#add_stats'

  get 'scenarios/:scenario_id/compare' => 'scenarios#compare', as: :compare_scenario
  get 'scenarios/:scenario_id/remote' => 'implementations#remote', as: :remote_implementation
  get 'scenarios/:scenario_id/implementations/:id/frame' => 'implementations#frame', as: :frame

  get 'tasks' => 'visulaization_tasks#index'

  get 'types' => 'types#index'

  root 'high_voltage/pages#show', id: 'home'

end

app/views/layouts/shared/_footer.html.haml
%footer
  %hr/
  .container
    .row
      .col-md-3
        %ul.list-unstyled
          %li= link_to "Home", page_path('home') , class: "active"
          %li= link_to "About", page_path('about')
          %li= link_to "Imprint", page_path('imprint')
      .col-md-3
        %ul.list-unstyled
          %li= link_to "Scenarios", scenarios_path
          %li= link_to "Libraries", libraries_path
          %li= link_to "Taxonomy", types_path
      .col-md-3
        %h1 wyvis
      .col-md-3
        The core idea behind wyvis is to allow for empirical evaluation and pilot testing with JavaScript visualization libraries in a comparable, repeatable and interactive way, while reducing the time and resources spend on preparations that are required for such tests.