config/routes.rb
Rails.application.routes.draw do
  resources :libraries

  get 'libraries/participation/:id' => 'libraries#participation', as: :library_participation

  resources :scenarios do
    resources :implementations
  end

  put 'implementations/:id/add_stats' => 'implementations#add_stats'

  get 'scenarios/:scenario_id/compare' => 'scenarios#compare', as: :compare_scenario
  get 'scenarios/:scenario_id/remote' => 'implementations#remote', as: :remote_implementation
  get 'scenarios/:scenario_id/implementations/:id/frame' => 'implementations#frame', as: :frame

  get 'tasks' => 'visulaization_tasks#index'

  get 'types' => 'types#index'

  root 'high_voltage/pages#show', id: 'home'

end

app/models/library.rb
class Library < ActiveRecord::Base
  include Transliterate
  serialize :meta_tags
  serialize :render_tech
  serialize :repo_participation_stats

  validates :name, :url, presence: true
  
  has_many :implementations, inverse_of: :library
  has_many :resources, inverse_of: :library
  has_and_belongs_to_many :visualization_types
  has_and_belongs_to_many :visualization_tasks

  before_save :fetch_github_info

  def fetch_github_info
    if has_github_repo
      
      repo = Octokit::Repository.from_url self.url_code

      client = Octokit::Client.new
      client.client_id = ENV["GITHUB_CLIENT_ID"]
      client.client_secret = ENV["GITHUB_SECRET"]
    

      begin
        # Get the weekly commit count for the 
        # repository owner and everyone else.
        # oldest (0) to most recent week (52)
        # {"all":[0,..,52],"owner":[0,..,52]}
        stats = client.participation_stats repo
        if !stats.nil?
          self.repo_participation_stats = stats.to_h;
        end
        
        # fetch repo information
        repository = client.repository repo

        self.repo_created_at = repository.created_at
        self.repo_pushed_at = repository.pushed_at
        self.repo_watchers_count = repository.subscribers_count
        self.repo_stargazers_count = repository.stargazers_count
        self.repo_forks_count = repository.forks_count
        self.repo_open_issues = repository.open_issues

        # Get the latest release data 
        latest_release = client.release repo.path + '/releases/latest'
        
        self.latest_release = latest_release.published_at
        self.current_version = latest_release.tag_name
      
      # if no releases are available we try tags
      rescue Octokit::NotFound
        begin
          tags = client.tags repo
          if !tags[0].nil?
            self.current_version = tags[0].name
            latest_tagged_commit = client.commit repo, tags[0].commit.sha

            self.latest_release = latest_tagged_commit.commit.committer.date
          end

        # neither is available
        rescue Octokit::Error => e
          puts self.name
          puts e
        end
      rescue Octokit::Error => e
        puts self.name
        puts e
      end

    end
  end

  def has_github_repo
    if self.url_code.nil?
      return false
    else
      return self.url_code.include? "github"
    end
  end

  def self.fetch_github_infos

  end
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  expose :library, attributes: :library_params
  expose(:libraries) { Library.order('LOWER(name) ASC') }
  expose(:libraries_rep) { LibraryDecorator.decorate_collection(libraries)}

  # GET /libraries
  def index
    respond_to do |f|
      f.html { render layout: "wide_content" }
      f.json { libraries }
    end
    
  end

  # GET /libraries/1
  def show
  end

  # GET /libraries/new
  def new
  end

  # GET /libraries/1/edit
  def edit
  end

  def participation
    respond_to do |f|
      f.js do
        json = library.repo_participation_stats.to_json
        render object: library, locals: {:json => json}
      end
        
    end
  end

  # POST /libraries
  def create
    if library.save
      redirect_to library, notice: 'Library was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /libraries/1
  def update
    if library.update(library_params)
      redirect_to library, notice: 'Library was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /libraries/1
  # DELETE /libraries/1.json
  def destroy
    library.destroy
    redirect_to libraries_url, notice: 'Library was successfully destroyed.'
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def library_params
      params.require(:library).permit(:name,:short,:description,:url,:license,:latest_version,:web_standards,:support)
    end
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/_form.html.haml
= simple_form_for(@library) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :short, hint: 'max. 150 characters', input_html: { maxlength: 150 }
    = f.input :discription
    = f.input :url
    = f.input :license
    = f.input :latest_version
    = f.input :web_standard, label: 'Web standards only? (e.g. SVG, Canvas, etc.)'
    = f.input :support

  .form-actions
    = f.button :submit, class: 'btn-success'

app/views/libraries/edit.html.haml
%h1 Editing #{link_to library.name, library}

= render 'libraries/partials/form'
%br/
.btn-group
  = link_to 'Back', libraries_path, class: 'btn btn-default'
  = link_to 'Show', library, class: 'btn btn-default'

app/views/libraries/index.html.haml
- content_for :title do
  = "Visualization Libraries"
.row
  .col-md-7.col-md-offset-1
    %h1.page-header Visualization Libraries
    %p.lead This is a list of JavaScript visualization libraries. Some of them focus on charting, some on particular visualizations and others are complete web graphing tools, capable of more complex visualizations.
.row
  .col-md-7.col-md-offset-1
    %hr/
    #thumb-container.row
      = render partial: 'libraries/partials/library_thumb', collection: libraries_rep, as: :lib
  .col-md-4.affix-details#affix
    = render partial: 'shared/live_search_field'
    = render partial: 'libraries/partials/library', collection: libraries_rep, as: :lib
      
%br/

app/views/libraries/new.html.haml
%h1.page-header New library

= render 'libraries/partials/form'
%br/
= link_to 'Back', libraries_path, class: 'btn btn-default'

app/views/libraries/participation.js.erb
;(function (window, $) {

  var $target = $( "#<%= library.transliterate_name %> .participation-graph" ),
      data = <%= json.html_safe %>;

  // calculate dates
  $.each(data, function (key, value) {
    for(var i = value.length - 1; i >= 0; i--) {
      var date = moment().subtract( 52 - i,"weeks").valueOf();
      value[i] = {count: value[i], date: date};
    }
  });

  // set up margins
  var margin = {top: 25, right: 10, bottom: 25, left: 10},
      width = $target.width() - margin.left - margin.right,
      height = 100 - margin.top - margin.bottom;

  // scales
  var x = d3.time.scale()
      .range([0, width])
      .domain(d3.extent(data.all, function(d) { return d.date; }));

  var y = d3.scale.linear()
      .range([height, 0])
      .domain(d3.extent(data.all, function(d) { return d.count; }));

  // prepare axis objects
  var x_axis_helper = d3.svg.axis()
      .scale(x)
      .orient("bottom");

  var y_axis_helper = d3.svg.axis()
      .scale(y)
      .orient("left");

  // function to draw the line
  var line = d3.svg.line()
      .x(function(d) { return x(d.date); })
      .y(function(d) { return y(d.count); });

  // setup svg container
  var svg = d3.select("#<%= library.transliterate_name %> .participation-graph")
        .append("svg")
          .attr("width", width + margin.left + margin.right)
          .attr("height", height + margin.top + margin.bottom)
        .append("g")
          .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

  // prepare groups for axis
  var x_axis = svg.append("g")
        .attr("class", "x axis")
        .attr("transform", "translate(0," + height + ")")
        .call(x_axis_helper);

  // var y_axis = svg.append("g")
  //       .attr("class", "y axis")
  //       .call(y_axis_helper);

  // create a path to represent the data as a line
  var path = svg.append("g")
        .attr("class", "path");

      path.append("path")
        .datum(data.all)
        .attr("d", line)
        .attr("class", "all line");

      // path.append("path")
      //   .datum(data.owner)
      //   .attr("d", line)
      //   .attr("class", "owner line");

  var marks = path.append("g")
          .attr("class", "marks")

      marks.selectAll("circle")
          .data(data.all).enter()
        .append("g")
          .attr("class", "mark")
        .append("circle")
          .attr("cx", function(d){return x(d.date);})
          .attr("cy", function(d){return y(d.count);})
          .attr("r", "4px");

      marks.selectAll(".mark")
        .append("text")
          .attr("class", "mark-text")
          .attr("x", function(d){return x(d.date);})
          .attr("y", -5)
          .attr("text-anchor", "middle")
          .text(function(d){return d.count;});
        

})(window, jQuery);

app/views/libraries/show.html.haml
%h1.page-header
  = library.name
-if notice
  .alert.alert-success
    %p#notice= notice

%p.lead
  = library.short
%p= link_to library.url, library.url
%p
  = library.description

.btn-group
  = link_to 'Edit', edit_library_path(library), class: 'btn btn-default'
  = link_to 'Back', libraries_path, class: 'btn btn-default'