config/routes.rb
Rails.application.routes.draw do
  resources :libraries

  get 'libraries/participation/:id' => 'libraries#participation', as: :library_participation

  resources :scenarios do
    resources :implementations
  end

  put 'implementations/:id/add_stats' => 'implementations#add_stats'

  get 'scenarios/:scenario_id/compare' => 'scenarios#compare', as: :compare_scenario
  get 'scenarios/:scenario_id/remote' => 'implementations#remote', as: :remote_implementation
  get 'scenarios/:scenario_id/implementations/:id/frame' => 'implementations#frame', as: :frame

  get 'tasks' => 'visulaization_tasks#index'

  get 'types' => 'types#index'

  root 'high_voltage/pages#show', id: 'home'

end

app/models/implementation.rb
class Implementation < ActiveRecord::Base
  include Transliterate
  
  validates :library_id, :scenario_id, presence: true

  belongs_to :scenario, inverse_of: :implementations
  belongs_to :library, inverse_of: :implementations

  before_save :set_name

  def dir_path
    self.scenario.dir_path + "/#{transliterate_name}"
  end

  def dir_url
    self.scenario.dir_url + "/#{transliterate_name}"
  end

  def script  
    File.open(dir_path + '/script.js').read
  end

  def styles  
    File.open(dir_path + '/styles.css').read
  end

  def script_url
    dir_url + "/script.js"
  end

  def styles_url
    dir_url + "/styles.css"
  end

  def resources
    paths = Dir.glob('public' + dir_url + '/lib/*.js')
    paths.each_index do |i|
      paths[i] = paths[i].sub('public', '')
    end
    return paths
  end

  def json
    self.to_json(
      :methods => [:script, :styles]
    )
  end

  private
    def set_name
      self.name = self.library.name
    end
end

app/controllers/implementations_controller.rb
class ImplementationsController < ApplicationController
  expose(:scenario)
  expose(:implementation, attributes: :implementation_params)
  expose(:library) { implementation.library }

  def new
  end

  # GET /implementations/1
  # GET /implementations/1.js
  def show    
    render layout: 'wide_content'
  end

  def remote
    @implementation = Implementation.find( params[:id] ).decorate
    @index = params[:index]
    
    respond_to do |format|
      format.js
    end
  end

  # GET /implmentations/1/frame
  def frame
    render layout: 'frame'
  end

  # GET /implmentations/1/edit
  def edit
  end

  # POST /scenarios/1/implementations
  def create
    if implementation.save
      redirect_to scenario, notice: 'Implementation was successfully created.'
    else
      render :new 
    end
  end

    # PATCH/PUT /implmentations/1
  def update
    if implementation.save
      redirect_to scenario_implementation_path(scenario,implementation), notice: 'Scenario was successfully updated.'
    else
      render :edit
    end
  end

  def add_stats
    new_value = params.require(:implementation)[:new_value].to_f

    if !new_value.nil?
      old_average = implementation.execution_time
      old_count = implementation.execution_count
      new_average = calc_new_average(old_count, old_average, new_value)

      implementation.execution_count += 1
      implementation.execution_time = new_average

      if implementation.save
        render 'add_stats.json', :locals => {:success => true}
      else
        render 'add_stats.json', :locals => {:success => false, :errors => implementation.errors}
      end
    else
      render 'add_stats.json', :locals => {:success => false, :errors => "no value"}
    end
  end

  # DELETE /implementations/1
  def destroy
    implementation.destroy
    redirect_to scenario, notice: 'Implementation was successfully destroyed.'
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def implementation_params
      p = params.permit(:scenario_id)
      p.merge params.require(:implementation).permit(:library_id, :execution_time, :update_time)
    end

    def calc_new_average(old_count, old_average, new_value)
      old_average + ((new_value - old_average) / (old_count + 1))
    end
end

app/helpers/implementations_helper.rb
module ImplementationsHelper
end

app/views/implementations/edit.html.haml
%h1 Editing #{link_to implementation.library.name, scenario_implementation_path(scenario, implementation)} implementation of #{link_to implementation.scenario.name, scenario}

= render 'implementations/partials/form'
= link_to "Delete", scenario_implementation_path(scenario, implementation), method: :delete, data: { confirm: 'Are you sure?' }

app/views/implementations/frame.html.haml
- content_for :style do
  :css
    html, body, #vis {
    margin: 0;
    padding: 0;
    width: 100%;
    height: 100%;
    overflow: scroll;
    }
  = stylesheet_link_tag implementation.styles_url
  - library.resources.where(content_type: 'css').each do |r|
    = stylesheet_link_tag r.url
  %style#styles

#vis
- library.resources.where(content_type: 'javascript').each do |r|
  = javascript_include_tag r.url
= javascript_include_tag scenario.script_url
= javascript_include_tag implementation.script_url
- implementation.resources.each do |url|
  = javascript_include_tag url

app/views/implementations/new.html.haml
%h1 New implementation of #{link_to scenario.name, scenario}

= render 'implementations/partials/form'
%br/

app/views/implementations/remote.js.erb
;(function () {
  var container =  $( "#container-<%= @index %>");

  container.find( ".implementation" ).replaceWith("<%= j (render partial: 'implementations/partials/implementation', object: @implementation) %>");
  container.find( ".implementation" )
           .wyvis();
  container.addClass("implementation-loaded");
})();

app/views/implementations/show.html.haml
- content_for :title do
  #{scenario.name}: #{library.name}

.row
  .col-md-6.col-md-offset-3
    %h1.page-header
      #{ link_to library.name, library} implementation of #{link_to scenario.name, scenario}
      .btn-group.btn-group-sm.pull-right{role: 'group'}
        = link_to scenario, class: 'btn btn-default', title: 'Return to ' + scenario.name do
          %span.glyphicon.glyphicon-arrow-left
        = link_to edit_scenario_implementation_path(scenario, implementation), class: 'btn btn-default', title: 'Edit' do
          %span.glyphicon.glyphicon-edit
          Edit
    -if notice
      .alert.alert-success
        %p#notice
          %span.glyphicon.glyphicon-check
          = notice
      %button.close{type: "button", data: {dismiss: "alert"}} &times;

= render partial: 'implementations/partials/implementation', object: implementation