config/routes.rb
Rails.application.routes.draw do
  resources :libraries

  get 'libraries/participation/:id' => 'libraries#participation', as: :library_participation

  resources :scenarios do
    resources :implementations
  end

  put 'implementations/:id/add_stats' => 'implementations#add_stats'

  get 'scenarios/:scenario_id/compare' => 'scenarios#compare', as: :compare_scenario
  get 'scenarios/:scenario_id/remote' => 'implementations#remote', as: :remote_implementation
  get 'scenarios/:scenario_id/implementations/:id/frame' => 'implementations#frame', as: :frame

  get 'tasks' => 'visulaization_tasks#index'

  get 'types' => 'types#index'

  root 'high_voltage/pages#show', id: 'home'

end

app/models/scenario.rb
class Scenario < ActiveRecord::Base
  include Transliterate

  validates :name, :description, :short, presence: true

  has_and_belongs_to_many :data_types
  has_and_belongs_to_many :visualization_tasks
  has_and_belongs_to_many :visualization_types
  has_many :implementations, inverse_of: :scenario, dependent: :destroy
  has_many :libraries, through: :implementations
  

  def script  
    File.open(dir_path + '/data.js').read
  end

  def dir_path
    "#{Rails.root.join('public','assets').to_s}/scenarios/#{transliterate_name}"
  end

  def dir_url
    "/assets/scenarios/#{transliterate_name}"
  end

  def script_url
    dir_url + '/data.js'
  end

  def has_interval?
    script.include? 'interval: true'
  end

  def json
    self.to_json(
      :methods => :script
    )
  end

  private
end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController
  expose(:scenarios)
  expose(:scenario, attributes: :scenario_params)
  expose(:scenario_dec) { scenario.decorate }
  expose(:implementations) {ImplementationDecorator.decorate_collection(scenario.implementations)}

  # GET /scenarios
  def index
  end

  # GET /scenarios/1
  def show
  end

  # GET /scenarios/new
  def new
  end

  # GET /implementations/compare/?ids[]
  def compare
    @implementations = ImplementationDecorator.decorate_collection( Implementation.where(id: params[:ids]).limit(2) )

    render layout: 'wide_content'
  end

  # GET /scenarios/1/edit
  def edit
  end

  # POST /scenarios
  def create
    if scenario.save
      redirect_to scenario, notice: 'Scenario was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /scenarios/1
  def update
    if scenario.save
      redirect_to scenario, notice: 'Scenario was successfully updated.'
    else
      render :edit 
    end
  end

  # DELETE /scenarios/1
  def destroy
    scenario.destroy
    redirect_to scenarios_url, notice: 'Scenario was successfully destroyed.'
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def scenario_params
      params.require(:scenario).permit(:name, :short, :description, :javascript)
    end
end

app/helpers/scenario_helper.rb
module ScenarioHelper
  
end

app/helpers/scenarios_helper.rb
module ScenariosHelper
end

app/views/scenarios/compare.html.haml
- content_for :title do
  = scenario.name

.row.scenario-container
  = form_tag('/',id: 'form-scenario-select', class: 'form-inline') do
    .form-group
      = select_tag :id, options_from_collection_for_select(scenarios, 'id', 'name', scenario.id), class: 'form-control'
  = scenario_dec.hash_tags
  %span.pull-right.hint Click to toggle details.
  .scenario-details
    %p.lead.short= scenario.short
    %p.description= scenario.description
.row.compare-container
  - 2.times do |i|
    .implementation-container{id: 'container-' + i.to_s}
      .top-controls
        = form_tag(remote_implementation_path(scenario, index: i), method: 'get', format: 'javascript', remote: true, class: 'form-inline form-impl-select') do
          .form-group
            = select_tag :id, options_from_collection_for_select(implementations, 'id', 'lib_name'), class: 'form-control', prompt: 'Select an implementation', onchange: 'javascript: $( this ).trigger("submit.rails")'
        %button.btn.btn-icon.btn-full-screen
          %span.glyphicon
        %button.btn.btn-icon.btn-lib-info
          %span.glyphicon
      .implementation
        .select-notification
          %h2 No implementation seleceted.
          %p Go ahead and select an implementation to compare it.
          = render partial: 'scenarios/partials/implementation_thumb', collection: scenario.implementations, locals: {index: i}

  - @implementations.each_with_index do |impl, i|
    :javascript
      $("#container-#{i} .form-impl-select select" ).val('#{impl.id}').trigger("change");

app/views/scenarios/edit.html.haml
- content_for :title do
  \∙ #{scenario.name}

%h1.page-header Editing #{link_to scenario.name, scenario}

= render 'scenarios/partials/form'

app/views/scenarios/index.html.haml
- content_for :title do
  Scenarios

%h1.page-header Scenarios

.row
  - scenarios.each do |scenario|
    .col-sm-4.col-md-3
      = link_to compare_scenario_path(scenario), class: 'link-thumb' do
        .thumbnail.scenario-thumb
          .caption
            %h3= scenario.name
            %p= scenario.short
          .badges
            = scenario.decorate.hash_tags

  -# .col-sm-4.col-md-3
  -#   = link_to new_scenario_path, class: 'link-thumb', title: 'Add a new scenario' do
  -#     .thumbnail.add-item-thumb
  -#       .plus
  -#         %div
  -#         %div

app/views/scenarios/new.html.haml
%h1 New scenario

= render 'scenarios/partials/form'
%br/
= link_to 'Back', scenarios_path, class: 'btn btn-default'

app/views/scenarios/show.html.haml
- content_for :title do
  #{scenario.name}

.btn-group.btn-group-xs{role: 'group'}
  = link_to 'Back to scenarios', scenarios_path, class: 'btn btn-default btn-small'
  = link_to edit_scenario_path(scenario), class: 'btn btn-default btn-small', title: 'Edit' do
    %span.glyphicon.glyphicon-edit
    Edit
%h1.page-header
  = scenario.name
-if notice
  .alert.alert-success
    %p#notice
      %span.glyphicon.glyphicon-check
      = notice
      %button.close{tape: "button", data: {dismiss: "alert"}} &times;

%p.lead
  = scenario.short
%p
  = scenario.description

%h2 Compare two Implementations
%p.lead Select any implementation to get started.
%p
  The comparison view allows you to easily see different interpretations of the scenario side by side. You can inspect and edit the source code right in the browser to explore possibilties and find out which library comforts you most.
.row
  = render partial: 'implementations/partials/implementation_thumb', collection: scenario.implementations
  .col-sm-4.col-md-3
    = link_to new_scenario_implementation_path(scenario), class: 'link-thumb', title: 'Add a new implementation' do
      .thumbnail.add-item-thumb
        .plus
          %div
          %div